"""Add phone_number to employees

Revision ID: 2d518eef70c7
Revises: f490887dee10
Create Date: 2026-07-16 21:27:55.129901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d518eef70c7'
down_revision = 'f490887dee10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.create_unique_constraint('uq_employees_phone_number', 'employees', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_employees_phone_number', 'employees', type_='unique')
    op.drop_column('employees', 'phone_number')
    # ### end Alembic commands ###
