"""Add task_type, relax trello_card_id and department_id nullability

Revision ID: 3d115fff2f54
Revises: 2d518eef70c7
Create Date: 2026-07-16 22:08:51.295925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d115fff2f54'
down_revision = '2d518eef70c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tasks',
        sa.Column(
            'task_type', sa.Enum('order', 'misc', name='task_type', native_enum=False),
            nullable=False, server_default='order',
        ),
    )
    op.alter_column('tasks', 'trello_card_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('tasks', 'current_department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'current_department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'trello_card_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('tasks', 'task_type')
    # ### end Alembic commands ###
