"""phase2 reminder schedule overdue trello member checklist reassignment

Revision ID: 470b837c8dae
Revises: 576f19bf5629
Create Date: 2026-07-17 00:24:26.838419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '470b837c8dae'
down_revision = '576f19bf5629'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('reminder_schedule', sa.JSON(), nullable=False))
    op.drop_column('app_settings', 'remind_time')
    op.add_column('departments', sa.Column('auto_reassign_after_48h', sa.Boolean(), nullable=False))
    op.add_column('employees', sa.Column('trello_member_id', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('day_left_notified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('reassignment_signaled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('reassigned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('trello_checklist_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'trello_checklist_id')
    op.drop_column('tasks', 'reassigned_at')
    op.drop_column('tasks', 'reassignment_signaled_at')
    op.drop_column('tasks', 'day_left_notified_at')
    op.drop_column('employees', 'trello_member_id')
    op.drop_column('departments', 'auto_reassign_after_48h')
    op.add_column('app_settings', sa.Column('remind_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_column('app_settings', 'reminder_schedule')
    # ### end Alembic commands ###
