"""Add trello_list_id to departments

Revision ID: 4aeafdfa9317
Revises: c54dee342844
Create Date: 2026-07-16 20:04:52.289003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aeafdfa9317'
down_revision = 'c54dee342844'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('trello_list_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'trello_list_id')
    # ### end Alembic commands ###
