"""add multi-stage task progression

Revision ID: 576f19bf5629
Revises: 3d115fff2f54
Create Date: 2026-07-16 23:22:08.788269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '576f19bf5629'
down_revision = '3d115fff2f54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('next_department_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_departments_next_department_id', 'departments', 'departments', ['next_department_id'], ['id'])
    op.add_column('tasks', sa.Column('previous_task_id', sa.Integer(), nullable=True))
    op.alter_column('tasks', 'deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('active', 'completed', 'overdue', 'stopped', 'pending_setup', name='task_status', native_enum=False),
               existing_nullable=False)
    op.drop_constraint('tasks_trello_card_id_key', 'tasks', type_='unique')
    op.create_index(op.f('ix_tasks_trello_card_id'), 'tasks', ['trello_card_id'], unique=False)
    op.create_foreign_key('fk_tasks_previous_task_id', 'tasks', 'tasks', ['previous_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tasks_previous_task_id', 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_trello_card_id'), table_name='tasks')
    op.create_unique_constraint('tasks_trello_card_id_key', 'tasks', ['trello_card_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('active', 'completed', 'overdue', 'stopped', 'pending_setup', name='task_status', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.alter_column('tasks', 'deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('tasks', 'previous_task_id')
    op.drop_constraint('fk_departments_next_department_id', 'departments', type_='foreignkey')
    op.drop_column('departments', 'next_department_id')
    # ### end Alembic commands ###
