"""Add penalty_rules table

Revision ID: 835647e37c2a
Revises: a95b0c221e79
Create Date: 2026-07-16 19:24:35.742077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835647e37c2a'
down_revision = 'a95b0c221e79'
branch_labels = None
depends_on = None


penalty_rules_table = sa.table(
    "penalty_rules",
    sa.column("department_id", sa.Integer),
    sa.column("min_hours_late", sa.Integer),
    sa.column("max_hours_late", sa.Integer),
    sa.column("score", sa.Integer),
)

# 8.2-band: foydalanuvchi tomonidan tasdiqlangan kechikish jadvali (department_id=NULL
# -> barcha yo'nalishlar uchun global). 96 soatdan keyingi bosqich hali kelishilmagan —
# admin keyinchalik shu jadvalga yangi qator qo'shishi kifoya, kodga tegish shart emas.
SEED_RULES = [
    {"department_id": None, "min_hours_late": 0, "max_hours_late": 24, "score": -1},
    {"department_id": None, "min_hours_late": 24, "max_hours_late": 48, "score": -2},
    {"department_id": None, "min_hours_late": 48, "max_hours_late": 72, "score": -5},
    {"department_id": None, "min_hours_late": 72, "max_hours_late": 96, "score": -8},
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penalty_rules',
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('min_hours_late', sa.Integer(), nullable=False),
    sa.Column('max_hours_late', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(penalty_rules_table, SEED_RULES)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('penalty_rules')
    # ### end Alembic commands ###
