"""Add brigade_id to employees

Revision ID: c54dee342844
Revises: 835647e37c2a
Create Date: 2026-07-16 19:34:08.960625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c54dee342844'
down_revision = '835647e37c2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('brigade_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_employees_brigade_id_brigades', 'employees', 'brigades', ['brigade_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_employees_brigade_id_brigades', 'employees', type_='foreignkey')
    op.drop_column('employees', 'brigade_id')
    # ### end Alembic commands ###
