"""Add app_settings singleton table

Revision ID: f490887dee10
Revises: 4aeafdfa9317
Create Date: 2026-07-16 20:28:32.315576

"""
from datetime import time

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f490887dee10'
down_revision = '4aeafdfa9317'
branch_labels = None
depends_on = None


app_settings_table = sa.table(
    "app_settings",
    sa.column("remind_time", sa.Time),
    sa.column("default_penalty_multiplier", sa.Float),
    sa.column("brigade_share_ratio", sa.Float),
    sa.column("balls_per_day_shift", sa.Integer),
)

# Bitta seed qator -- avvalgi kod-konstantalarga (penalty_service.py) mos
# boshlang'ich qiymatlar bilan. Jadval SINGLETON: doim shu bitta qator
# o'qiladi/yangilanadi, yangi qator qo'shilmaydi.
SEED_ROW = {
    "remind_time": time(8, 30),
    "default_penalty_multiplier": 1.0,
    "brigade_share_ratio": 0.33,
    "balls_per_day_shift": 5,
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('remind_time', sa.Time(), nullable=False),
    sa.Column('default_penalty_multiplier', sa.Float(), nullable=False),
    sa.Column('brigade_share_ratio', sa.Float(), nullable=False),
    sa.Column('balls_per_day_shift', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(app_settings_table, [SEED_ROW])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
